### ISSUE TITLE
Spelling mistakes at the main page in English

### ISSUE THREAD

**Issue by DenTaliy** [Areso/Oblache#129]
**Discription**
-spelling mistakes in description if the 

**Preconditions:**

**Reproduction steps:**

1. open https://oblache.areso.pro/
2. 
3.

**Expected Result:**
Expected :[There is no spelling mistakes]

What we really wanted to see, how it should work

**Actual result:**
Actual   :
![Screenshot_11](https://github.com/Areso/Oblache/assets/163882998/c94a38c7-dc24-4305-aba6-80b322e5aeb7)]

What we see after we reproduced the bug

**Environment:**

 - OS: 
 - Выпуск	Windows 11 Pro
 - Версия	22H2
 - Дата установки	‎16.‎10.‎2023
 - Сборка ОС	22621.3007
 - Взаимодействие	Windows Feature Experience Pack 1000.22681.1000.0
 
**Priority(High, Medium, Low)**
- Low

**Severity(Blocker, Critical, Major, Minor, Trivial)**
- Trivial

**Application:**
-

**Link to Allure report:**
https://areso.github.io/Oblache/

**Additional context**

**Comment by Areso** [comment]
Fixed
