### ISSUE TITLE
Time-zones of server and host are different

### ISSUE THREAD

**Issue by Yaroslavcher** [Areso/Oblache#130]
**Discription**
- Time-zone in "Creation date" field is not the same as local host time-zone

**Preconditions:**

Local host time-zone is UTC+3
User "yaroslavcher@gmail.com" is registered

**Reproduction steps:**

1. Open oblache.areso.pro in browser.
2. Click Login button.
3. Input "yaroslavcher@gmail.com" in login field.
4. Input "password" in password field.
5. Click Login button.
6. Click Databases tab.
7. Click Create new DB button.

**Expected Result:**
Time in "Creation date" field is the same as local host time.

**Actual result:**
Time in "Creation date" field is NOT the same as local host time.

**Screenshot:**
![2024-03-20_dbTimeNotLocalTime](https://github.com/Areso/Oblache/assets/105816783/90f596da-b176-4d8f-a26c-c22c6a0ac3bf)

**Environment:**
OS: Ubuntu 22.04.3 LTS
Browser: Firefox
 
**Priority(High, Medium, Low)**
Low

**Severity(Blocker, Critical, Major, Minor, Trivial)**
Minor

**Application:**
n/a

**Link to Allure report:**
n/a

**Additional context**
n/a

**Comment by Areso** [comment]
Now, all the events are displayed explicitly as Event, UTC.
