### ISSUE TITLE
Semantic mistake in Terms of Use

### ISSUE THREAD

**Issue by Yaroslavcher** [Areso/Oblache#131]
**Discription**
Semantic mistake in Terms of Use

**Preconditions:**

Not necessary

**Reproduction steps:**

1. Open https://oblache.areso.pro/register.html
2. Click on "Terms of Use" link

**Screenshot:**
![2024-03-20_tos-page_ошибка в тексте](https://github.com/Areso/Oblache/assets/105816783/c3e0744d-e9da-4456-94a3-7446b05dd10c)

**Expected Result:**
n/a

**Actual result:**
n/a

**Environment:**
n/a
 
**Priority(High, Medium, Low)**
- Low

**Severity(Blocker, Critical, Major, Minor, Trivial)**
- Minor

**Comment by Areso** [comment]
Fixed
