### ISSUE TITLE
Text size is too big to be visible on Terms of Use page

### ISSUE THREAD

**Issue by Yaroslavcher** [Areso/Oblache#132]
**Discription**
Text size is too big to be visible on Terms of Use page

**Preconditions:**
Scale (zoom) in browser is 100%.

**Reproduction steps:**

1. Open oblache.areso.pro in browser
2. Click on "Terms of Use" link in the footer
3. Scroll to the end of page

**Expected Result:**
All text is visible on the page.

**Actual result:**
Part of text is not visible on the page.

**Screenshot:**
![2024-03-20_tos-page_обрезан текст снизу](https://github.com/Areso/Oblache/assets/105816783/8e45cd0e-68fe-4f02-984c-4e2ffc2e4ca8)

**Environment:**

 - OS: Ubuntu 22.04.3 LTS
 - browser: Firefox
 
**Priority(High, Medium, Low)**
Low

**Severity(Blocker, Critical, Major, Minor, Trivial)**
Trivial

**Application:**
n/a

**Link to Allure report:**
n/a

**Additional context**
All text is visible if change zoom to 90%.

**Comment by Areso** [comment]
Fixed
