### ISSUE TITLE
Add qstatus

### ISSUE THREAD

**Issue by Areso** [Areso/Oblache#21]

**Comment by Areso** [comment]
/qty orders create
/qty orders delete
subroutine for identifying stuck tasks
/qty stuck tasks create
/qty stuck tasks delete
/newregs is unverified email, unverified status
registration->verifying email->verifying status

**Comment by Areso** [comment]
Okay, for now the idea is done, and the endpoint is working (GET /qstatus, not authentication so far).
To AQA:
r.code=200
```
{
    "queue_db_create_orders": 0,
    "queue_db_delete_orders": 0,
    "number_of_stuck_tasks": 0,
    "db_manual_delete_count": 4,
    "acc_with_no_region_count": 1
}
```
Check keys (they should be present)
Check response values, type int, values from 0 to any positive number.

**Comment by lambotik** [comment]
Done
