### ISSUE TITLE
Bug: You can create site with empty fields "Git Repo Source"

### ISSUE THREAD

**Issue by zomlik** [Areso/Oblache#275]
**Description**
- The backend returns a phrase where there are two spaces after "There is"

**Preconditions:**

If necessary

**Reproduction steps:**

1.  Create new Static Site with empty fields "Git Repo Source"

**Expected Result:**
Error 

What we really wanted to see, how it should work

**Actual result:**
Created successfully , but new site get Current status:  error_creating

What we see after we reproduced the bug

**Environment:**

 - OS: 
 - Выпуск	Windows 11 Pro
 - Версия	22H2
 - Дата установки	‎16.‎10.‎2023
 - Сборка ОС	22621.3007
 - Взаимодействие	Windows Feature Experience Pack 1000.22681.1000.0
 
**Priority(High, Medium, Low)**
- Low

**Severity(Blocker, Critical, Major, Minor, Trivial)**
- Minor

**Application:**
-

**Link to Allure report:**
https://areso.github.io/Oblache/

**Additional context**

**Comment by Areso** [comment]
Yeap, I should check it.

**Comment by Areso** [comment]
![image](https://github.com/user-attachments/assets/73d9f0dd-d74d-4c75-83a4-dce7aff0b015)
Fixed
