### ISSUE TITLE
Bug: Error "you cannot undeploy this site" when  deleting a static site with status "error_creating"

### ISSUE THREAD

**Issue by zomlik** [Areso/Oblache#277]
**Reproduction steps:**

1. Delete a static site with status "error_creating"

**Expected Result:**
The Static Site have been deleted 

**Actual result:**
Error:  you cannot undeploy this site

What we see after we reproduced the bug

**Environment:**

 - OS: 
 - Выпуск	Windows 11 Pro
 - Версия	22H2
 - Дата установки	‎16.‎10.‎2023
 - Сборка ОС	22621.3007
 - Взаимодействие	Windows Feature Experience Pack 1000.22681.1000.0
 
**Priority(High, Medium, Low)**
- High

**Severity(Blocker, Critical, Major, Minor, Trivial)**
- Critical

**Application:**
-

**Link to Allure report:**
https://areso.github.io/Oblache/

**Additional context**

**Comment by Areso** [comment]
Not a bug.
Resources in "error" states ("error", "error creating", "error deleting", "error threshold") aren't in state from which automation could work.
So far such resources couldn't be deleted by automation, because no automation knows theirs state.
