### ISSUE TITLE
Bug: Incorrect value in the "is site deploy allowed?" field on the Status page

### ISSUE THREAD

**Issue by zomlik** [Areso/Oblache#284]
**Reproduction steps:**

1. Open Status page

**Expected Result:**
is site deploy allowed? = 1 if allowed and 0 if not

**Actual result:**
is site deploy allowed? = 0 if allowed and 1 if not

![image](https://github.com/user-attachments/assets/2414f7be-ab36-4970-959e-1a33768b41b5)

**Environment:**

 - OS: 
 - Выпуск	Windows 11 Pro
 - Версия	22H2
 - Дата установки	‎16.‎10.‎2023
 - Сборка ОС	22621.3007
 - Взаимодействие	Windows Feature Experience Pack 1000.22681.1000.0
 
**Priority(High, Medium, Low)**
- Low

**Severity(Blocker, Critical, Major, Minor, Trivial)**
- Trivial

**Application:**
-

**Link to Allure report:**
https://areso.github.io/Oblache/

**Additional context**

**Comment by zomlik** [comment]
![image](https://github.com/user-attachments/assets/569c1011-3383-4ea8-80a3-2ad640e36b15)

**Comment by Areso** [comment]
changed to POST method, so should be fixed (at least in terms of caching data from this endpoint)
