### ISSUE TITLE
Bug: The static site is being created with an invalid branch

### ISSUE THREAD

**Issue by zomlik** [Areso/Oblache#286]
**Reproduction steps:**
1. Create a new static site with an invalid branch

**Expected Result:**
....

**Actual result:**
Current status: error_creating
The site is available at the created url
**Environment:**

 - OS: 
 - Выпуск	Windows 11 Pro
 - Версия	22H2
 - Дата установки	‎16.‎10.‎2023
 - Сборка ОС	22621.3007
 - Взаимодействие	Windows Feature Experience Pack 1000.22681.1000.0
 
**Priority(High, Medium, Low)**
- Medium

**Severity(Blocker, Critical, Major, Minor, Trivial)**
- Major

**Link to Allure report:**
https://areso.github.io/Oblache/

**Comment by Areso** [comment]
fixed, please check and confirm

**Comment by Areso** [comment]
@zomlik
