### ISSUE TITLE
Bug: Error "Some general exception" when making a request to /db_create without authorization

### ISSUE THREAD

**Issue by zomlik** [Areso/Oblache#288]
**Reproduction steps:**
curl -i -X POST \
-d '{"dbtype":3, "dbversion":5, "env": 3,"region":3}' \
https://dbend.areso.pro/db_create -v

**Expected Result:**
Status code: 401
Body:
{
    "content": "msg[5]: unauthenticated"
}

**Actual result:**
Status code: 500
Body:
Some general exception

**Environment:**

 - OS: 
 - Выпуск	Windows 11 Pro
 - Версия	22H2
 - Дата установки	‎16.‎10.‎2023
 - Сборка ОС	22621.3007
 - Взаимодействие	Windows Feature Experience Pack 1000.22681.1000.0
 
**Priority(High, Medium, Low)**
- Medium

**Severity(Blocker, Critical, Major, Minor, Trivial)**
- Major

**Link to Allure report:**
https://areso.github.io/Oblache/

**Comment by Areso** [comment]
Fixed, please confirm
