### ISSUE TITLE
catch up wrong db_env with 400 http code err

### ISSUE THREAD

**Issue by Areso** [Areso/Oblache#36]

**Comment by Areso** [comment]
added this check to the code

**Comment by Areso** [comment]
payload
```
{
    "content": "error: DB environment isn't found or isn't available for order"
}
```
r.code=400

**Comment by lambotik** [comment]
============================== 1 passed in 0.45s ==============================
PASSED [100%]

Method POST: post_db_create_wrong_value_env
https://dbend.areso.pro/db_create
Status code: 400
Response body:  {
    "content": "error: DB environment isn't found or isn't available for order"
}

{'content': "error: DB environment isn't found or isn't available for order"}
Assert expected status code: 400 == Response status code: 400
Value: error: DB environment isn't found or isn't available for order
is presence in key: content

Process finished with exit code 0
