### ISSUE TITLE
changing password endpoint

### ISSUE THREAD

**Issue by Areso** [Areso/Oblache#76]

**Comment by Areso** [comment]
Obl-76 is rolling out

**Comment by Areso** [comment]
It's working, yay.
To AQA:
we have a test, where we register two users.
Based on that test, I'd like to extend it to a suite, where we also changing passwords for them
`/password_update` which takes cookie-sid, and this payload
`{"current_password":"", "new_password":""}'
Add following tests:
1) attempting to do that without providing sid
2) attempting without providing current password
3) attempting without providing new password
4) attempting with providing _wrong_ current password
5) full correct attempting.

**Comment by lambotik** [comment]
Done
https://github.com/Areso/Oblache/pull/85
