### ISSUE TITLE
is_logged

### ISSUE THREAD

**Issue by Areso** [Areso/Oblache#96]

**Comment by Areso** [comment]
curl -X POST -H "Content-Type: application/json" https://dbend.areso.pro/is_logged -v
curl -X POST -H "Content-Type: application/json" -d '{"web": 1}' https://dbend.areso.pro/is_logged -v
curl -X POST --cookie "sid=de333e01-b0fd-41b1-ba6a-2913a34d0fe2" -H "Content-Type: application/json" https://dbend.areso.pro/is_logged -v
curl -X POST --cookie "sid=de333e01-b0fd-41b1-ba6a-2913a34d0fe2" -H "Content-Type: application/json" -d '{"web": 1}' https://dbend.areso.pro/is_logged -v

To AQA:
1) check is_logged - should return 401 if sid isn't provided
2) check is_logged, -d '{"web":1}' - should return 302 if sid isn't provided
3) check is_logged with correct sid - 200
4) check is_logged with incorrect sid - 401
5) check is_logged with correct sid, web: 1 - 200
6) check is_logged with incorrect sid, web: 1 - 302
so, 6 checks

**Comment by lambotik** [comment]
Done
